language: r

os:
  - linux
  
r:
  - release
  - oldrel
  - devel

repos:
  CRAN: https://cloud.r-project.org
  
services:
  - mongodb

addons:
  apt:
    packages:
      - libv8-dev
      
cache: packages
latex: false
warnings_are_errors: false

before_script:
  - sleep 15
  - mongo IntegrationTest --eval 'db.createUser({user:"travis",pwd:"test",roles:["dbAdmin"]});'
  
after_success:
  - Rscript -e 'covr::codecov()'
