# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: 
  - release
  
sudo: false
cache: packages
latex: false
warnings_are_errors: false

#before_install:
#  - tlmgr install texinfo
#  - tlmgr install index

after_success:
  - Rscript -e 'covr::codecov()'